# fly.toml app configuration file generated for trade-simulation-game on 2024-07-16T10:54:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about this file.
#

app = "trade-simulation-game"
primary_region = "sjc"

[build]
  builder = "paketobuildpacks/builder-jammy-base"
  buildpacks = ["heroku/python"]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"
